# Generated by Django 5.0.1 on 2024-01-25 15:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkSpace',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('end_station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_space_end_station', to='api.weatherstation')),
                ('start_station', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_space_start_station', to='api.weatherstation')),
            ],
            options={
                'verbose_name': 'WorkSpace',
                'verbose_name_plural': 'WorkSpaces',
            },
        ),
        migrations.AddField(
            model_name='worktime',
            name='work_space',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.workspace'),
            preserve_default=False,
        ),
    ]
