# Generated by Django 5.0.1 on 2024-01-25 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_workspace_worktime_work_space'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspace',
            name='end_station',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='work_space_end_station', to='api.weatherstation'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='workspace',
            name='start_station',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='work_space_start_station', to='api.weatherstation'),
            preserve_default=False,
        ),
    ]
