# Generated by Django 5.0.1 on 2024-01-18 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_employeecard_weather_station'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeecard',
            name='weather_station',
        ),
        migrations.AddField(
            model_name='employeecardlog',
            name='weather_station',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.weatherstation'),
        ),
    ]
