# Generated by Django 5.0.1 on 2024-01-25 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_workspace_end_station_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeecard',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.employee'),
        ),
    ]
